### ISSUE TITLE
Issue with order of elements in envelope

### ISSUE THREAD

**Issue by nobre84** [bulldog2011/pico#3]
Hi, I'm trying nano and pico, with a soap 1.1 webservice, the wsdl generated model classes in nano are stored on a LinkedHashmap which preserves ordering, however on ios pico it isn't able to achieve the same ordered output (as it uses NSDictionary which can't be ordered), which I suspect may be the culprit of an error.
How to make sure the elements reach the xml envelope in the order they appear in the Model ?

I worked around the issue by using Matt Gallagher's OrderedDictionary in every place such as this:
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];

Also in PicoBindingSchema:

@interface PicoBindingSchema : NSObject {

....
    OrderedDictionary *_property2ElementSchemaMapping;
    OrderedDictionary *_property2AttributeSchemaMapping;
....

This way the modeled atribute order is kept, and the web-service I am consuming is happy. I don't know if this is an issue in this particular web-service, or if ordering is really supposed to be respected.

Thanks very much for this awesome work!

**Comment by bulldog2011** [comment]
Hi,

This for your suggestion, this is a good feature request!

I will try to integrate OrderedDictionary you suggested in Pico, will let you know when it's done.

Many thanks!
-William

**Comment by bulldog2011** [comment]
OrderedDictionary has been integrated in Pico and mwsc, if possible, please re-download latest pico source and mwsc zip package to verify.

Thx!
-William

**Comment by nobre84** [comment]
Hi, I have tested and the new mwsc generated files + pico source works properly with ordered fields output!
