### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by marckaraujo** [bulldog2011/pico#9]
Have a way to print the XML before send it?
So we can work with the exception...

**Comment by hellobyte-dev** [comment]
There is a debug property on PicoSOAPClient or PicoXMLClient which your specific service client extending:
https://github.com/bulldog2011/pico/blob/master/pico/PicoSource/WebService/PicoSOAPClient.h
Set it to true for runtime request/response message debugging.

**Comment by marckaraujo** [comment]
Thanks, it works.

Can I ask you one more help?
I need to add this namespace, is this possible?

![captura de tela 2014-08-04 22 32 18](https://cloud.githubusercontent.com/assets/3084181/3805911/62528d1c-1c40-11e4-93d2-6e65bf6a897f.png)

**Comment by marckaraujo** [comment]
I just create a hard code on it, thanks anyway.
